//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneView.Models
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class admin
    {
        public byte adminID { get; set; }
        public string password { get; set; }

        public static admin Login(admin admin)
        {
            using (var context = new Entities())
            {
                var result = context.admin.Where(a => a.adminID == admin.adminID).FirstOrDefault<admin>();
                MD5TransferAndVerify md5 = new MD5TransferAndVerify();
                if (result == null)
                {
                    return null;
                }
                else
                {
                    if (md5.Verify(result.password, admin.password))
                    {
                        return result;
                    }
                    else
                    {
                        return null;
                    }
                }
                
            }
        }
    }

}
