//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class commentLikeMes
    {
        public long messageID { get; set; }
        public long commentID { get; set; }
        public string senderID { get; set; }
        public string receiverID { get; set; }
        public System.DateTime time { get; set; }
    
        public virtual user user { get; set; }
        public virtual user user1 { get; set; }
    }
}
