//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public comment()
        {
            this.commentLikeMes = new HashSet<commentLikeMes>();
            this.commentReplyMes = new HashSet<commentReplyMes>();
            this.commentReply = new HashSet<commentReply>();
        }
    
        public long commentID { get; set; }
        public string userID { get; set; }
        public short scenicID { get; set; }
        public decimal mark { get; set; }
        public string commentContent { get; set; }
        public decimal commentLike { get; set; }
        public System.DateTime commentTime { get; set; }
    
        public virtual scenicSpot scenicSpot { get; set; }
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commentLikeMes> commentLikeMes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commentReplyMes> commentReplyMes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<commentReply> commentReply { get; set; }
    }
}
