//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneView.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<admin> admin { get; set; }
        public virtual DbSet<answer> answer { get; set; }
        public virtual DbSet<comment> comment { get; set; }
        public virtual DbSet<commentLikeMes> commentLikeMes { get; set; }
        public virtual DbSet<commentReplyMes> commentReplyMes { get; set; }
        public virtual DbSet<message> message { get; set; }
        public virtual DbSet<note> note { get; set; }
        public virtual DbSet<noteLikeMes> noteLikeMes { get; set; }
        public virtual DbSet<question> question { get; set; }
        public virtual DbSet<scenicImage> scenicImage { get; set; }
        public virtual DbSet<scenicPos> scenicPos { get; set; }
        public virtual DbSet<scenicSpot> scenicSpot { get; set; }
        public virtual DbSet<strategy> strategy { get; set; }
        public virtual DbSet<strategyImage> strategyImage { get; set; }
        public virtual DbSet<user> user { get; set; }
        public virtual DbSet<userInfo> userInfo { get; set; }
    }
}
