//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SceneView.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class note
    {
        public int noteID { get; set; }
        public Nullable<int> userID { get; set; }
        public Nullable<short> scenicID { get; set; }
        public string title { get; set; }
        public string noteContent { get; set; }
        public Nullable<decimal> noteLike { get; set; }
        public Nullable<System.DateTime> noteTime { get; set; }
    
        public virtual scenicSpot scenicSpot { get; set; }
        public virtual user user { get; set; }
    }
}
